<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Users Report</title>
</head>
<body>
    <div style="margin-bottom:25px;"><strong>Report generated by</strong></div>
    <table style="border-collapse: collapse;">
        <thead>
            <tr>
                <th style="border-bottom:2pt solid black;">
                    <strong>Especificaciones de {{$equipos->Nombre_Tipo_Equipo}}</strong>
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach ($especificacion as $especif)
            <tr>
                <td style="border-bottom:1pt solid black;">
                    {{$especif->Nombre_Especificacion_Equipo}}
                </td>
                <td style="border-bottom:1pt solid black;">
                    {{$especif->Especificacion_Equipo}}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</body>
</html>